/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as FailureRouteImport } from './routes/failure'
import { Route as HttpRouteImport } from './routes/http'
import { Route as HttpFailureRouteImport } from './routes/http-failure'
import { Route as RpcRouteImport } from './routes/rpc'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const FailureRoute = FailureRouteImport.update({
  id: '/failure',
  path: '/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpRoute = HttpRouteImport.update({
  id: '/http',
  path: '/http',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpFailureRoute = HttpFailureRouteImport.update({
  id: '/http-failure',
  path: '/http-failure',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcRoute = RpcRouteImport.update({
  id: '/rpc',
  path: '/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/failure': typeof FailureRoute
  '/http': typeof HttpRoute
  '/http-failure': typeof HttpFailureRoute
  '/rpc': typeof RpcRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/failure': typeof FailureRoute
  '/http': typeof HttpRoute
  '/http-failure': typeof HttpFailureRoute
  '/rpc': typeof RpcRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/failure': typeof FailureRoute
  '/http': typeof HttpRoute
  '/http-failure': typeof HttpFailureRoute
  '/rpc': typeof RpcRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/details'
    | '/diagnostics'
    | '/failure'
    | '/http'
    | '/http-failure'
    | '/rpc'
    | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/details'
    | '/diagnostics'
    | '/failure'
    | '/http'
    | '/http-failure'
    | '/rpc'
    | '/api/$'
  id:
    | '__root__'
    | '/'
    | '/details'
    | '/diagnostics'
    | '/failure'
    | '/http'
    | '/http-failure'
    | '/rpc'
    | '/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailsRoute: typeof DetailsRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  FailureRoute: typeof FailureRoute
  HttpRoute: typeof HttpRoute
  HttpFailureRoute: typeof HttpFailureRoute
  RpcRoute: typeof RpcRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failure': {
      id: '/failure'
      path: '/failure'
      fullPath: '/failure'
      preLoaderRoute: typeof FailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http': {
      id: '/http'
      path: '/http'
      fullPath: '/http'
      preLoaderRoute: typeof HttpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-failure': {
      id: '/http-failure'
      path: '/http-failure'
      fullPath: '/http-failure'
      preLoaderRoute: typeof HttpFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc': {
      id: '/rpc'
      path: '/rpc'
      fullPath: '/rpc'
      preLoaderRoute: typeof RpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailsRoute: DetailsRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  FailureRoute: FailureRoute,
  HttpRoute: HttpRoute,
  HttpFailureRoute: HttpFailureRoute,
  RpcRoute: RpcRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
